dist: bionic

language: node_js

node_js:
    - 13

services:
    - docker

git:
    clone: false

branches:
   only:
   - develop

before_install:
    - docker swarm init
    - git clone https://github.com/appdevdesigns/travis-appbuilder.git
    - cd travis-appbuilder
    - scripts/installer.sh

script:
    - npm run test

after_failure:
    - scripts/dump_logs.sh

notifications:
        slack: digiserve-workspace:TP2WoZPOV4G2zlzgBQDF9K01

