dist: bionic

language: node_js

node_js:
    - 13

services:
    - docker

git:
    clone: false

before_install:
    - git clone https://github.com/echu888/travis-appbuilder.git
    - cd travis-appbuilder
    - npm install
    - docker swarm init
    - scripts/installer.sh

script:
    - pwd
    - echo $HOME
    - npm run test
