DROP TRIGGER IF EXISTS `EXPENSE_REPORT_STATUS_UPDATE`;

DELIMITER $$
CREATE TRIGGER `EXPENSE_REPORT_STATUS_UPDATE`
AFTER UPDATE
ON `AB_DonationTracking_ExpenseReport` FOR EACH ROW
BEGIN
    DECLARE STATUS_QX_APPROVE_VALUE varchar(255) DEFAULT "1612340065524"; -- QX Approved

    IF (OLD.`Status` = STATUS_QX_APPROVE_VALUE
    AND NEW.`Status` != STATUS_QX_APPROVE_VALUE)
    THEN
        CALL `REVIEW_EXPENSE_REPORT_INBOX`(NEW.`uuid`);
    END IF;

END $$

DELIMITER ;
