DROP EVENT IF EXISTS `REVIEW_EXPENSE_REPORT_INBOX_JOB`;

DELIMITER $$

CREATE EVENT `REVIEW_EXPENSE_REPORT_INBOX_JOB`
ON SCHEDULE EVERY '1' MONTH -- Monthly
DO
BEGIN

    CALL `REVIEW_EXPENSE_REPORT_INBOX`(NULL);

END$$

DELIMITER ;
