name: build-on-release
on:
  release:
    types: [published]
jobs:
  publish:
    name: Push production image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y.%m.%d')"

      - name: Get simple tag name
        id: tag
        run: echo "::set-output name=tag::$(basename ${{ github.ref }})"

      - name: Check out the ab-production-image repo
        uses: actions/checkout@v2
        with:
          repository: appdevdesigns/ab-production-image
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: |
            digiserve/ab-sails-api:${{ steps.tag.outputs.tag }}
            digiserve/ab-sails-api:latest
          #  digiserve/ab-sails-api:${{ steps.date.outputs.date }}
          build-args: AB_GITHUB_COMMIT=${{ github.sha }}
